#RoastEngine settings
#Sat Sep 19 20:06:23 PDT 2026
effectsVolume=0.9
fieldOfView=70.0
lastServer=34.216.210.173
masterVolume=1.0
mouseSensitivity=1.0
musicVolume=1.0
playerName=Player9745
shadersEnabled=true
showFps=true
vsync=true
